### ISSUE TITLE
Bad Credentials Error

### ISSUE THREAD

**Issue by Digized** [jonathanGB/ScheduleGeneratorWebApp#9]
Hey,
I am getting a bad credentials error when trying to login to my uottawa account.. I think its related to uottawa now requiring the whole email instead of the left part of the email.

I looked a bit into it and it looks like the url has changed
to https://adfs.uottawa.ca/adfs/ls/?client-request-id=6a07eab6-36d7-4ccd-2045-0180020000b2
and body to UserName: zzafa015@uottawa.ca
Password: password
AuthMethod: FormsAuthentication

**Comment by jonathanGB** [comment]
Thanks @Digized for bringing this up. Indeed, I realized that (yet again) uoZone changed their authentication system (I graduated from uOttawa in May, hence I was not aware myself, a friend of mine pointed that out as well this afternoon).

If you're curious about how the fix was implemented, see the commit referenced previously in this thread. There were changes to URLs, as well as the username, and property names. On top of that, they added levels of complexity with redirections to `SAML` and client IDs to authenticate.

I've tested and it seems to work now!
